{
 "title": "clickhouse Copy",
 "time": { "from": "1969-12-31T23:48:18.876Z", "to": "1970-01-01T00:12:14.780Z" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n  toStartOfInterval(wall_time_dt, INTERVAL 3 HOUR) AS time,\r\n  comm,\r\n  avg(latency_ms) AS avg_latency_ms\r\nFROM audit.tracing_events\r\nGROUP BY time, comm\r\nORDER BY time ASC\r\n",
     "rawQuery": "/* grafana dashboard=clickhouse, user=1 */\nSELECT\r\n  toStartOfInterval(wall_time_dt, INTERVAL 3 hour) AS time,\r\n  comm,\r\n  avg(latency_ms) AS avg_latency_ms\r\nFROM audit.tracing_events\r\nGROUP BY time, comm\r\nORDER BY time ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "count event type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "audit",
     "dateTimeColDataType": "wall_time_dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n  event_type,\r\n  comm,\r\n  filename,\r\n  count() AS total_events\r\nFROM audit.tracing_events\r\nGROUP BY\r\n  event_type,\r\n  comm,\r\n  filename\r\nORDER BY\r\n  total_events DESC\r\nLIMIT 100\r\n",
     "rawQuery": "/* grafana dashboard=clickhouse, user=1 */\nSELECT\r\n  event_type,\r\n  comm,\r\n  filename,\r\n  count() AS total_events\r\nFROM audit.tracing_events\r\nGROUP BY\r\n  event_type,\r\n  comm,\r\n  filename\r\nORDER BY\r\n  total_events DESC\r\nLIMIT 100",
     "round": "0s",
     "table": "tracing_events"
    }
   ]
  },
  {
   "title": "Max latency per node and event type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    node_name,\r\n    event_type,\r\n    argMax(comm, latency_ms) AS comm_with_max_latency,\r\n    argMax(filename, latency_ms) AS filename_with_max_latency,\r\n    argMax(cgroup_name, latency_ms) AS cgroup_name_with_max_latency,\r\n    MAX(latency_ms) AS max_latency_ms\r\nFROM audit.tracing_events\r\nGROUP BY node_name, event_type\r\nORDER BY max_latency_ms DESC\r\n",
     "rawQuery": "/* grafana dashboard=clickhouse, user=1 */\nSELECT\r\n    node_name,\r\n    event_type,\r\n    cgroup_name,\r\n    argMax(comm, latency_ms) AS comm_with_max_latency,\r\n    argMax(filename, latency_ms) AS filename_with_max_latency,\r\n    MAX(latency_ms) AS max_latency_ms\r\nFROM audit.tracing_events\r\nGROUP BY node_name, event_type\r\nORDER BY max_latency_ms DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total syscall by node",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n  node_name,\r\n  event_type,\r\n  count() AS total_syscalls\r\nFROM audit.tracing_events\r\nGROUP BY\r\n  node_name,\r\n  event_type\r\nORDER BY\r\n  node_name,\r\n  total_syscalls DESC\r\n",
     "rawQuery": "/* grafana dashboard=clickhouse, user=1 */\nSELECT\r\n  node_name,\r\n  event_type,\r\n  count() AS total_syscalls\r\nFROM audit.tracing_events\r\nGROUP BY\r\n  node_name,\r\n  event_type\r\nORDER BY\r\n  node_name,\r\n  total_syscalls DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "ROLLUP number of comm by cgroup ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n  cgroup_id,\r\n  cgroup_name,\r\n  comm,\r\n  count() AS total_events\r\nFROM audit.tracing_events\r\nGROUP BY ROLLUP(comm, cgroup_id, cgroup_name)\r\nORDER BY\r\n  total_events DESC",
     "rawQuery": "/* grafana dashboard=clickhouse, user=1 */\nSELECT\r\n  cgroup_id,\r\n  cgroup_name,\r\n  comm,\r\n  count() AS total_events\r\nFROM audit.tracing_events\r\nGROUP BY ROLLUP(comm, cgroup_id, cgroup_name)\r\nORDER BY\r\n  total_events DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total syscall by day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    toStartOfDay(wall_time_dt) AS day,\r\n    COUNT(*) AS syscall_count\r\nFROM audit.tracing_events\r\nGROUP BY day\r\nORDER BY day\r\n",
     "rawQuery": "/* grafana dashboard=clickhouse, user=1 */\nSELECT\r\n    toStartOfDay(wall_time_dt) AS day,\r\n    COUNT(*) AS syscall_count\r\nFROM audit.tracing_events\r\nGROUP BY day\r\nORDER BY day",
     "round": "0s"
    }
   ]
  },
  {
   "title": "avg(latency) by comm",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n  comm,\r\n  event_type,\r\n  cgroup_name,\r\n  avg(latency_ms) AS avg_latency_ms\r\nFROM audit.tracing_events\r\nGROUP BY\r\n  event_type,\r\n  cgroup_name,\r\n  comm\r\nORDER BY\r\n  avg_latency_ms DESC\r\nLIMIT 100",
     "rawQuery": "/* grafana dashboard=clickhouse, user=1 */\nSELECT\r\n  comm,\r\n  event_type,\r\n  cgroup_name,\r\n  avg(latency_ms) AS avg_latency_ms\r\nFROM audit.tracing_events\r\nGROUP BY\r\n  event_type,\r\n  cgroup_name\r\n  comm\r\nORDER BY\r\n  avg_latency_ms DESC\r\nLIMIT 100",
     "round": "0s"
    }
   ]
  }
 ]
}