// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: ebpf_event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EbpfEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Pid                 uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Uid                 uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Comm                string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	Filename            string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ReturnCode          int64                  `protobuf:"varint,6,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	TimestampNs         uint64                 `protobuf:"varint,7,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	TimestampNsExit     uint64                 `protobuf:"varint,8,opt,name=timestamp_ns_exit,json=timestampNsExit,proto3" json:"timestamp_ns_exit,omitempty"`
	LatencyNs           uint64                 `protobuf:"varint,9,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	EventType           string                 `protobuf:"bytes,10,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	NodeName            string                 `protobuf:"bytes,11,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	User                string                 `protobuf:"bytes,12,opt,name=user,proto3" json:"user,omitempty"`
	Ppid                uint32                 `protobuf:"varint,13,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Gid                 uint32                 `protobuf:"varint,14,opt,name=gid,proto3" json:"gid,omitempty"`
	CgroupId            uint64                 `protobuf:"varint,15,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	CgroupName          string                 `protobuf:"bytes,16,opt,name=cgroup_name,json=cgroupName,proto3" json:"cgroup_name,omitempty"`
	UserPid             uint32                 `protobuf:"varint,17,opt,name=user_pid,json=userPid,proto3" json:"user_pid,omitempty"`
	UserPpid            uint32                 `protobuf:"varint,18,opt,name=user_ppid,json=userPpid,proto3" json:"user_ppid,omitempty"`
	TimestampUnixMs     int64                  `protobuf:"varint,19,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	ContainerId         string                 `protobuf:"bytes,20,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerImage      string                 `protobuf:"bytes,21,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	ContainerLabelsJson map[string]string      `protobuf:"bytes,22,rep,name=container_labels_json,json=containerLabelsJson,proto3" json:"container_labels_json,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EbpfEvent) Reset() {
	*x = EbpfEvent{}
	mi := &file_ebpf_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EbpfEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EbpfEvent) ProtoMessage() {}

func (x *EbpfEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ebpf_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EbpfEvent.ProtoReflect.Descriptor instead.
func (*EbpfEvent) Descriptor() ([]byte, []int) {
	return file_ebpf_event_proto_rawDescGZIP(), []int{0}
}

func (x *EbpfEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *EbpfEvent) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EbpfEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *EbpfEvent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EbpfEvent) GetReturnCode() int64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *EbpfEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *EbpfEvent) GetTimestampNsExit() uint64 {
	if x != nil {
		return x.TimestampNsExit
	}
	return 0
}

func (x *EbpfEvent) GetLatencyNs() uint64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *EbpfEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EbpfEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EbpfEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EbpfEvent) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *EbpfEvent) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *EbpfEvent) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

func (x *EbpfEvent) GetCgroupName() string {
	if x != nil {
		return x.CgroupName
	}
	return ""
}

func (x *EbpfEvent) GetUserPid() uint32 {
	if x != nil {
		return x.UserPid
	}
	return 0
}

func (x *EbpfEvent) GetUserPpid() uint32 {
	if x != nil {
		return x.UserPpid
	}
	return 0
}

func (x *EbpfEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *EbpfEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *EbpfEvent) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *EbpfEvent) GetContainerLabelsJson() map[string]string {
	if x != nil {
		return x.ContainerLabelsJson
	}
	return nil
}

type CollectorAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorAck) Reset() {
	*x = CollectorAck{}
	mi := &file_ebpf_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorAck) ProtoMessage() {}

func (x *CollectorAck) ProtoReflect() protoreflect.Message {
	mi := &file_ebpf_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorAck.ProtoReflect.Descriptor instead.
func (*CollectorAck) Descriptor() ([]byte, []int) {
	return file_ebpf_event_proto_rawDescGZIP(), []int{1}
}

func (x *CollectorAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CollectorAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ebpf_event_proto protoreflect.FileDescriptor

const file_ebpf_event_proto_rawDesc = "" +
	"\n" +
	"\x10ebpf_event.proto\x12\x02pb\"\xf6\x05\n" +
	"\tEbpfEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1f\n" +
	"\vreturn_code\x18\x06 \x01(\x03R\n" +
	"returnCode\x12!\n" +
	"\ftimestamp_ns\x18\a \x01(\x04R\vtimestampNs\x12*\n" +
	"\x11timestamp_ns_exit\x18\b \x01(\x04R\x0ftimestampNsExit\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\t \x01(\x04R\tlatencyNs\x12\x1d\n" +
	"\n" +
	"event_type\x18\n" +
	" \x01(\tR\teventType\x12\x1b\n" +
	"\tnode_name\x18\v \x01(\tR\bnodeName\x12\x12\n" +
	"\x04user\x18\f \x01(\tR\x04user\x12\x12\n" +
	"\x04ppid\x18\r \x01(\rR\x04ppid\x12\x10\n" +
	"\x03gid\x18\x0e \x01(\rR\x03gid\x12\x1b\n" +
	"\tcgroup_id\x18\x0f \x01(\x04R\bcgroupId\x12\x1f\n" +
	"\vcgroup_name\x18\x10 \x01(\tR\n" +
	"cgroupName\x12\x19\n" +
	"\buser_pid\x18\x11 \x01(\rR\auserPid\x12\x1b\n" +
	"\tuser_ppid\x18\x12 \x01(\rR\buserPpid\x12*\n" +
	"\x11timestamp_unix_ms\x18\x13 \x01(\x03R\x0ftimestampUnixMs\x12!\n" +
	"\fcontainer_id\x18\x14 \x01(\tR\vcontainerId\x12'\n" +
	"\x0fcontainer_image\x18\x15 \x01(\tR\x0econtainerImage\x12Z\n" +
	"\x15container_labels_json\x18\x16 \x03(\v2&.pb.EbpfEvent.ContainerLabelsJsonEntryR\x13containerLabelsJson\x1aF\n" +
	"\x18ContainerLabelsJsonEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\fCollectorAck\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage2A\n" +
	"\x0eEventCollector\x12/\n" +
	"\n" +
	"SendEvents\x12\r.pb.EbpfEvent\x1a\x10.pb.CollectorAck(\x01B!Z\x1febpf_loader/internal/grpc/pb;pbb\x06proto3"

var (
	file_ebpf_event_proto_rawDescOnce sync.Once
	file_ebpf_event_proto_rawDescData []byte
)

func file_ebpf_event_proto_rawDescGZIP() []byte {
	file_ebpf_event_proto_rawDescOnce.Do(func() {
		file_ebpf_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ebpf_event_proto_rawDesc), len(file_ebpf_event_proto_rawDesc)))
	})
	return file_ebpf_event_proto_rawDescData
}

var file_ebpf_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ebpf_event_proto_goTypes = []any{
	(*EbpfEvent)(nil),    // 0: pb.EbpfEvent
	(*CollectorAck)(nil), // 1: pb.CollectorAck
	nil,                  // 2: pb.EbpfEvent.ContainerLabelsJsonEntry
}
var file_ebpf_event_proto_depIdxs = []int32{
	2, // 0: pb.EbpfEvent.container_labels_json:type_name -> pb.EbpfEvent.ContainerLabelsJsonEntry
	0, // 1: pb.EventCollector.SendEvents:input_type -> pb.EbpfEvent
	1, // 2: pb.EventCollector.SendEvents:output_type -> pb.CollectorAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ebpf_event_proto_init() }
func file_ebpf_event_proto_init() {
	if File_ebpf_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ebpf_event_proto_rawDesc), len(file_ebpf_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ebpf_event_proto_goTypes,
		DependencyIndexes: file_ebpf_event_proto_depIdxs,
		MessageInfos:      file_ebpf_event_proto_msgTypes,
	}.Build()
	File_ebpf_event_proto = out.File
	file_ebpf_event_proto_goTypes = nil
	file_ebpf_event_proto_depIdxs = nil
}
